### ISSUE TITLE
Auto create License

### ISSUE THREAD

**Issue by wurstbroteater** [h3ssto/ddueruem-web#112]
On fresh start automatically create default license if not already exists.

**Comment by wurstbroteater** [comment]
I tried https://docs.djangoproject.com/en/4.0/howto/writing-migrations/ . I added the 0001_initial.py to core/fileupload/migrations and https://docs.djangoproject.com/en/4.0/howto/writing-migrations/ but it doesnt work.  Here are some tutorials which I found but havent tried yet : 
https://dev.to/guin/writing-a-django-data-migration-with-real-world-example-40m
https://simpleisbetterthancomplex.com/tutorial/2017/09/26/how-to-create-django-data-migrations.html

@Bishares  Can you please checkout branch `issue-112` and check if you can get it to work?

**Comment by wurstbroteater** [comment]
The problem was that we splitted the models.py into a folder containing model classes as files. This caused strange dependcies in migration process which were not fixable easily so I reverted back to 1 models.py file containg all relevant classes

**Comment by Bishares** [comment]
this might help
https://docs.djangoproject.com/en/4.0/howto/initial-data/

**Comment by Bishares** [comment]
The solution was adding the migrationfiles to gitignore.

We are now in a late stage of developlment where we prepopulate our database. So committing the migrations is recommended: https://stackoverflow.com/questions/28035119/should-i-be-adding-the-django-migration-files-in-the-gitignore-file
