### ISSUE TITLE
SVG Feature Model Viewer

### ISSUE THREAD

**Issue by h3ssto** [h3ssto/ddueruem-web#132]
# Performance Improvements
- [x] Meassure parsing vs render time
- [x] Does a pre-computed SVG help?

# UI

- [x]  Context Menu (compare with FeatureIDE?)
- [x] Collapsing the children of a feature (Context Menu | Strg+Click?)
    - [x] Collapses as intended
    - [x] Adds a number to the feature indicating (1) the number of direct children and (2) the number of all sub-features
- [x] Top aligned and horizontally centered (panning only if overflows, maybe only horizontally)
- [x] Search bar for searching features 
    - [x] On ENTER collapse all features above the parent feature of the searched feature and below its direct child features
    - [x] Highlight features with *close enough match* by color
- [x] Click on feature: collapses all above features and "focuses" on the clicked feature
- [x]  +/- Buttons for explicitly zooming in, no automatic resizing

# Color Grading
- [x] Mapping of Features <-> Integers and Integers to Color Scale (for coloring features with respect to TBA attributes, e.g., number of direct children)

# Other improvements
- [x]  Write abstract features italic, do not care about them when coloring
- [x]  Vertical spacing configurable
- [x]  Collapse siblings

**Comment by Eixix** [comment]
Precomputing the svg is propably not really helpful, as it needs to be reparsed to gain all interactivity anyway. This will lead to a performance hit as well. The big feature model takes 100ms to parse and around 20 to render.

**Comment by Eixix** [comment]
We implemented our own search approach as a proposal. We think that someone doesn't know where he is with the above approach. Possible refinements:
- always put the highlighted node into the middle of the screen
- hide all sibling nodes

**Comment by Eixix** [comment]
When color coding what about abstract features?

**Comment by Eixix** [comment]
Write abstract features italic, do not care about them when coloring

**Comment by Eixix** [comment]
collapse siblings

**Comment by Eixix** [comment]
less vertical spacing

**Comment by Eixix** [comment]
When searching for one Feature and it exists multiple times, the search will only find one feature

**Comment by h3ssto** [comment]
Features typically only exist once in a feature model, so this is not an issue.

**Comment by h3ssto** [comment]
I don't know how performance-helly it is, but how good would it work, if the search starts searching after 2-3 letters?

**Comment by Eixix** [comment]
@h3ssto Searching live is performant enough. Should we implement levenshtein distance instead of includes to make it more tolerant to typos?
