### ISSUE TITLE
DSGVO page

### ISSUE THREAD

**Issue by Bishares** [h3ssto/ddueruem-web#134]
implement the DSGVO Page in the new Vue frontend. You can use the old React DSGVO component as basis.

**Comment by Bishares** [comment]
@h3ssto Für die DSGVO Seite fehlt uns immer noch eine service mail adresse :)

**Comment by Bishares** [comment]
DSGVO with new vuetify styles was added in commit [ba685a8](https://github.com/h3ssto/ddueruem-web/commit/ba685a82416b677f302a32b697ab7868107a2c86)

**Comment by lukharsch** [comment]
done
