### ISSUE TITLE
Pages with tables

### ISSUE THREAD

**Issue by Bishares** [h3ssto/ddueruem-web#136]
There are several pages which will have a table that fetches data from the backend. Their behavior is often very similar. Pages that need to be implemented:

- [x] #137
- [x] #138
- [x] #146 
- [x] #140

**Comment by Bishares** [comment]
implement the pages that display tables in the new Vue frontend. You can use the old React components as basis. Also make sure to prepare the communication with the services that will fill the tables in the pages.

**Comment by lukharsch** [comment]
Added GET and DELETE Functionality for TAGS page (missing: issue #144 )

**Comment by lukharsch** [comment]
I removed the checks, pages are finished when backend services works correctly with CRUD :)

**Comment by lukharsch** [comment]
done
