### ISSUE TITLE
Add auth check when performing DELETE on tags

### ISSUE THREAD

**Issue by lukharsch** [h3ssto/ddueruem-web#144]
Right now, when wanting to delete a tag, it performs the deletion no matter if I'm the owner of the tag. Solution: Change the backend to check if the user that wants to perform the deletion (by token) is the one who is the owner of the tag.

**Comment by Bishares** [comment]
This is likely already working.
The `TagsViewSet` in the backend has the following permissions enabled:
`permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]`

This should be confirmed to be working through a unit test. @nhoehne

**Comment by nhoehne** [comment]
[There is a unit test testing for this behaviour.](https://github.com/h3ssto/ddueruem-web/blob/f27fa73adcec7e6dfb6e7165170089b46ccb1610/backend/core/fileupload/tests.py#L200)
