### ISSUE TITLE
Tags page

### ISSUE THREAD

**Issue by lukharsch** [h3ssto/ddueruem-web#146]
CRUD actions to implement:

- [x] GET
- [ ] DELETE (see issue #144 )
- [x] CREATE

@h3ssto Should it be possible to UPDATE existing tags?

**Comment by Bishares** [comment]
The frontend styling was added with commit 699a42f

**Comment by Bishares** [comment]
only staff or admin can create public tags. Alternate: staff or admin have to confirm a publification of a private tag.
