### ISSUE TITLE
Add i18n support frontend

### ISSUE THREAD

**Issue by h3ssto** [h3ssto/ddueruem-web#21]
Support of i18n the backend is built-in in Django, what options do we have for the frontend (could we use the same i18n yaml for both?).

**Comment by wurstbroteater** [comment]
As far as I can see, the backend already supports that, because `settings.py`  contains 
```python
USE_I18N = True
```

**Comment by Eixix** [comment]
The existing django translation file might be served via a URL and then cached to the webbrowser (choose a valid caching strategy) to translate all strings. This way we have a central file to edit all translations.

**Comment by wurstbroteater** [comment]
For backend Transifex could be a good choice, see: https://www.transifex.com/django-rest-framework-1/django-rest-framework/
But it has pricing!

**Comment by wurstbroteater** [comment]
**Problem**
Backend: At the moment we can not translate every Exception Message we get. For example  simpleJWT supports i18n but the translations are not  always correct. Therefore we only can do partial translations in the backend. This is not good. A better approach would be to do translations only in the frontend. This needs to be discussed @Eixix @h3ssto @Bishares 
**Postboned** until this is solved.

**Comment by wurstbroteater** [comment]
**Solution:**
The backend sends english messages only and the frontend does the translation
