### ISSUE TITLE
Switch registering to asynchronous emails

### ISSUE THREAD

**Issue by Eixix** [h3ssto/ddueruem-web#218]
When clicking register in the frontend it only receives an answer from the backend when the mail was sent out. This takes a lot of time. The email sending should be done asychronously.

**Comment by nhoehne** [comment]
Es gibt zwei Möglichkeiten wie man das implementieren kann:

* Man startet einen neuen Thread, der die Email versendet
* Man erstellt eine Tabelle in der Datenbank in die zu versendende Emails eingetragen werden und nutzt dann einen Job Scheduler, der alle x Minuten läuft und alle Emails versendet

Ich hab jetzt erstmal die erste Option [implementiert](https://github.com/h3ssto/ddueruem-web/commit/a12da9ab451061e35d7076e14a4a78994460303a), die ist deutlich simpler. Die zweite Option hätte aber den Vorteil, dass man auch Fehlerbehandlung (z.B. Retries falls der E-Mailserver down ist) implementieren könnte.
