### ISSUE TITLE
Sampling: Basic Sampling Support

### ISSUE THREAD

**Issue by h3ssto** [h3ssto/ddueruem-web#22]
Sampling is a fundamental analysis technique for configurable systems. Two main variants are of practical relevance
a) Uniform Random Sampling, where the samples are statistically representative of the configuration space
b) t-Wise Sampling, where the samples cover all t-wise interaction between features

ddueruem is expected to possess an interface to BURST (@acherm et al.) in 2022:Q1 as well as own capabilities for URS.
How t-wise sampling will be realized is TBA.

Ideas:
* Samples should be generated automatically for all uploads (e.g., 1,000 URS, 2-wise, 3-wise)
* Users should be able to see / download / comment / reference available samples
* Logged-in users should be able to request samples with specific parameters
* Users should be able to access sampler performance in suitable formats

**Comment by wurstbroteater** [comment]
This issue has been closed because implementation is not realizable yet
