### ISSUE TITLE
Deleting features

### ISSUE THREAD

**Issue by Eixix** [h3ssto/ddueruem-web#222]

**Comment by Eixix** [comment]
Only features without cross tree constraints

**Comment by h3ssto** [comment]
TODO:
* [ ] Support "easy" removals (i.e., features that have no children)
* [ ] Support removal via slicing using FeatureIDE as a service

**Comment by h3ssto** [comment]
This is done, or @LukasOsti?

**Comment by LukasOsti** [comment]
This is done.
