### ISSUE TITLE
Feature Model Family View

### ISSUE THREAD

**Issue by h3ssto** [h3ssto/ddueruem-web#227]
![image](https://user-images.githubusercontent.com/58979585/185620843-a32f42df-5240-4ef6-9c56-7b7ce850827f.png)

Each feature model family (e.g., the BusyBox version history) has a view consisting of 3 major sections.

1) Header: Name, Description, maybe direct download links
2) Data view: 4 Plots depicting the evolution of the FM over time (e.g., #features, #ctc, #SAT, ...)
3) FM List: A sortable list where concrete versions of a feature model may be accessed (Version, version comment (e.g., commit message), #features, ...)

**Comment by lukharsch** [comment]
done
