### ISSUE TITLE
Feature: Take Home Analysis

### ISSUE THREAD

**Issue by h3ssto** [h3ssto/ddueruem-web#23]
As `ddueruem-web` will not be able to fulfill all requests for analysis, users should have the possibility to configure an analysis and then download respective `docker-compose.yaml` and related files to execute the analysis on their own metal, with little additional effort.

Planned analysis for which this feature should be available:
* BDD generation
* URS, t-wise Sampling

**Comment by wurstbroteater** [comment]
This issue has been closed because implementation is not realizable with the given information.
