### ISSUE TITLE
optional: create artifact of the test results (probably a txt file) if there are any failures/errors

### ISSUE THREAD

**Issue by Bishares** [h3ssto/ddueruem-web#25]
### should be done
* [ ] trigger an email if a build fails
* [ ] don't merge on failing tests
### optional stuff
* [ ] optional: create artifact of the test results (probably a txt file) if there are any failures/errors
* [ ] Have an optional setting to "always renew cache on pull request"

**Comment by wurstbroteater** [comment]
Postboned till we actually have artifacts

**Comment by Bishares** [comment]
The pipeline automatically fails on failing tests. Triggering email is overrated. An artifact is not needed, we have the sonarqube dashboard for test analysis.
