### ISSUE TITLE
Bulk Upload of Feature Model Histories

### ISSUE THREAD

**Issue by h3ssto** [h3ssto/ddueruem-web#286]
Currently, we only support the uploading of one file at a time.

However, for many real-world feature models, with thousands of version, this is not really usable.
Therefore, we need a "bulk" upload form, allowing to provide an archive (e.g., zip) or the selection of multiple files in the file chooser and uploading them all at once.

In addition, there should be the possibility to specify a regular expression to map filenames to displayed versions.

For testing, consider this repository: https://github.com/h3ssto/busybox-evohist

**Comment by lukharsch** [comment]
- Form of bulk upload UI

**Comment by lukharsch** [comment]
- [x] Frontend
    - [x] For the MVP, it is (imo) enough to use a static Feature Model name (derived from the individual file name), a static description (with the timestamp of upload) and a static versioning system (starting with 1.0.0 and from there one incrementing the major version: 2.0.0, 3.0.0, etc).
- [ ] Backend:
    - [ ] Change Model to enable bulk upload. The FormData object we send to the backend right now is something like this: `label: "xyz", description: "xyz", file: "xyz", version: "1.0.0", family: "BusyBox", tags: { key: "value", key: "value" }, ...`. In order to support bulk upload, I think of changing the model to accept something like this: `files: [ { label: "xyz", description: "xyz", file: "xyz", version: "1.0.0" }, { label: "xyz2", description: "xyz2", file: "xyz2", version: "2.0.0" }, { ... } ], family: "BusyBox", tags: { key: "value", key: "value", ... }`. This way, we are able to upload many files with just one FormData. 
    - [ ] Change email-verification service, so that the user have to only confirm once per upload and not once per file uploaded.
    - [ ] When we also want to accept the upload of zipped archives, we have to implement the logic to unzip and process the archive in the backend.

**Comment by lukharsch** [comment]
done
