### ISSUE TITLE
Delete Feature Models

### ISSUE THREAD

**Issue by lukharsch** [h3ssto/ddueruem-web#310]
@nhoehne it should be possible to delete feature models. I already see an endpoint for that in the backend, but I assume that this endpoint is only for deleting unconfirmed files (`files/uploaded/unconfirmed/delete/`). Could you please have a look at that and maybe implement DELETE option for deleting all files (also confirmed) under the `files/` endpoint? Also, please make sure to check the token and that the user is only allowed to delete his own files.

**Comment by nhoehne** [comment]
The `files/` endpoint already allows for the deletion of files. There was, however, no test for this behaviour, so [I added one](https://github.com/h3ssto/ddueruem-web/blob/dev/backend/core/fileupload/tests.py#L767).
