### ISSUE TITLE
Tests for file-upload

### ISSUE THREAD

**Issue by Eixix** [h3ssto/ddueruem-web#32]
Write tests for the frontend. Maybe GUI tests?

**Comment by Bishares** [comment]
basic file upload tests are merged with #46

**Comment by Bishares** [comment]
I can mock the axios stuff like this
https://jestjs.io/docs/mock-functions#mocking-modules

**Comment by Bishares** [comment]
So because we use typescript the mocking has to be declared like this:
https://stackoverflow.com/a/55351900/12263454

**Comment by Bishares** [comment]
We should follow this principle
https://kentcdodds.com/blog/write-fewer-longer-tests

**Comment by Bishares** [comment]
debugging tests in vscode can be enabled like this:
https://create-react-app.dev/docs/debugging-tests/#debugging-tests-in-visual-studio-code

**Comment by Bishares** [comment]
to test the react-select (the `<Select \>` ) this had to be added
https://testing-library.com/docs/ecosystem-react-select-event/
