### ISSUE TITLE
Make artifacts comparable

### ISSUE THREAD

**Issue by lukharsch** [h3ssto/ddueruem-web#334]

**Comment by lukharsch** [comment]
- CSV in table with sortable filtering options and hiding columns
- all other text files should display as is (text form)
- all files should have a download button

**Comment by lukharsch** [comment]
- collapsable buttons
- download buttons

**Comment by h3ssto** [comment]
If I remember correctly @lukharsch, this feature was implemented together with the Vue 3 migration? Can you confirm and close this issue once merged into dev.

**Comment by lukharsch** [comment]
@h3ssto it was implemented in vue2. I will close this issue and instead make one for the migration (which is partially already done, should not be complicated to do the remaining stuff)
