### ISSUE TITLE
Shortname datamodel not updated after edit

### ISSUE THREAD

**Issue by Bishares** [h3ssto/ddueruem-web#341]
The shortname display of nodes is not properly updated after the name of a node has been edited.

How to reproduce:
1. open http://localhost:8080/feature-model/new
2. Click on "View" in the toolbar and check the "Short Name" checkbox -> all nodes with name length <= 8 have "..." added to them, larger ones are trimmed at char 8 and also have "..." added
3. Uncheck the checkbox again
4. Right click on any node and edit the name
5.  Click on "View" in the toolbar and check the "Short Name" checkbox
    * What currently happens: the old name with the "..." logic is displayed
    * What should happen: the new name with the "..." logic is displayed

**Comment by tomatenhans** [comment]
Bug still exists in:

- [x] frontendVue3
- [x] frontend
