### ISSUE TITLE
Deleting highlighted constraints does not remove coloring in tree

### ISSUE THREAD

**Issue by Bishares** [h3ssto/ddueruem-web#344]
How to reproduce:
1. create some constraint
2. press the chip of the constraint to highlight it in the tree
3. press the garbage can next to the constraint
4. result
    - expected: chip is removed and highlighting as well
    - actual: only chip is removed and highlighting stays
5. additional problem: the color seems to be still "reserved" for the removed chip. Usually when creating multiple constraints they recieve colors in this order: red -> orange -> blue-ish -> ...When creating a new constraint after this behavior it recieves the 2. color (orange) not the first one (red).

before delete:
![image](https://user-images.githubusercontent.com/38129103/231888078-117807fd-cd6f-42d8-9950-3a9cf5ded8bc.png)

after delete:
![image](https://user-images.githubusercontent.com/38129103/231888220-04908a4b-e47d-4a12-b92f-8b76b9d26109.png)

after addition of second constraint:
![image](https://user-images.githubusercontent.com/38129103/231888721-ccd19bb7-0182-40a7-922a-480b3fcf33c3.png)

**Comment by tomatenhans** [comment]
Bug still exists in:
- [x] frontend, also the following bug with the wrong coloring
- [X] frontendVue3
