### ISSUE TITLE
Edited constraint highlights wrong nodes

### ISSUE THREAD

**Issue by Bishares** [h3ssto/ddueruem-web#345]
How to reproduce:
1. Create constraint "Feature A" AND "Feature B"
2. click the chip and see "Feature A" and "Feature B" properly highlighted
3. click edit next to the chip and change the constaint to "Root" AND "Feature B"
    - expected: Root and "Feature B" node are colored
    - actual: Root, "Feature A" and "Feature B" node are colored

initial coloring:
![image](https://user-images.githubusercontent.com/38129103/231890816-b4d6c512-097c-4b93-9e3a-59c08a795908.png)

wrong color after editing:
![image](https://user-images.githubusercontent.com/38129103/231890949-4e3ddc8f-6528-4a83-806a-b0e773ed69d2.png)

**Comment by tomatenhans** [comment]
Bug still exists in:
- [X]  frontendVue3 
- [x] frontend
