### ISSUE TITLE
Console errors occur when working with the constraint view

### ISSUE THREAD

**Issue by Bishares** [h3ssto/ddueruem-web#346]
You can reproduce this by running the cypress tests in constraints.cy.js. When doing lots of stuff in the constraint view it will throw this error into the console multiple times. It does not seem to affect the user or performance. However the cypress tests fail because of this error.

![image](https://user-images.githubusercontent.com/38129103/231894444-326dd1be-a492-4362-9eed-184c6b034de7.png)

**Comment by tomatenhans** [comment]
Bug still exists in:

- [X] frontendVue3 
- [x]   frontend
