### ISSUE TITLE
Pressing "hide right siblings" twice adds wrong pseudo node

### ISSUE THREAD

**Issue by Bishares** [h3ssto/ddueruem-web#349]
How to reproduce:

1.  Right click "Feature A" -> click "hide nodes" -> click "hide right siblings" => "Feature B" disappears correctly
2. Right click "Feature A" again -> click "hide nodes" -> click "hide right siblings" => "Feature B" re-appears correctly, but another pseudo node on the left side appears

![image](https://user-images.githubusercontent.com/38129103/232025691-7004d74a-4dc1-4664-9248-d284f875c6a4.png)

**Comment by Bishares** [comment]
I am actually not sure what the intended behavior for clicking "hide right siblings" twice is. 

For "Hide all other nodes on every level" it does the hiding once. Multiple clicks do nothing, except if other nodes have been expanded

**Comment by Bishares** [comment]
double clicking the ghost node makes it invisible. Clicking "hide left siblings" on "Feature A" while there is the invisible node left of it causes this error:

![image](https://user-images.githubusercontent.com/38129103/232048287-b0998ac9-4a9d-46d9-af95-d68e711636d1.png)

**Comment by tomatenhans** [comment]
Bug still exists in:

- [X] frontendVue3
- [x]  frontend
