### ISSUE TITLE
Clicking the edit button in family page does not work

### ISSUE THREAD

**Issue by Bishares** [h3ssto/ddueruem-web#351]
Clicking the edit button always brings the user to the details page of that family. The click event for the whole table column is probably prioritized over the button click event.
![image](https://user-images.githubusercontent.com/38129103/233500628-c7caa695-0846-4b29-b476-f967d4856133.png)

**Comment by MeisterSeSe** [comment]
Fixed for Vue2. In Vue3 this is not an issue but editing is not working yet.

**Comment by MeisterSeSe** [comment]
<img width="941" alt="image" src="https://github.com/OBDDimal/variability.dev/assets/105605891/4ef0e734-2806-4ce4-95ad-6352384141a0">
Uploading and editing histories in the Vue3 frontend in History Tab does not work in combination with the backend.
