### ISSUE TITLE
Initial Data Privacy

### ISSUE THREAD

**Issue by wurstbroteater** [h3ssto/ddueruem-web#38]
Django App: `core`

### Backend Tasks
* [x] Serve DSGVO self-disclosure as a Markdown file

### Frontend Tasks
* [x] Login Modal w/ link to data privacy disclaimer page 
* [x] User Opt-In-Confirmation (Modal?)
* [x] Data Privacy Disclaimer page

### Misc Tasks
* [x] Research what needs to go in the data privacy disclaimer
* [x] Document 
    * [x] What user data is stored
    * [x] For which purpose
    * [x] How it is processed 
    * [x] What happens on account termination 
* [x] Are there special data privacy laws for other nationals (EU, US, ...) we legally have to obey (as a non-commercial tool) or does DSGVO conformance suffice in all cases?

**Comment by Bishares** [comment]
bundesregierung has their dsgvo also in the header, i will do it similar

https://www.bundesregierung.de/breg-de

**Comment by Bishares** [comment]
Our DSGVO ist based on [this](https://www.datenschutz.org/datenschutzerklaerung-website/#datenschutzerklaerung-fuer-eine-website-vorlage-zum-download) template. The following points have been discussed:

Aktuell sammeln wir folgende personenbezogenen daten:

### Registrieren
- e-mail-adresse beim registrieren

### Fileupload
- email wird zu dem file gelinkt

### local storage
- userStr (beinhaltet das ganze user objekt in klartext)

### in der db die user table
- es gibt noch ein institute feld und isStaff flag (wird noch irgendwann in der GUI ergänzt nehme ich an?)
- das datum der registrierung ist vermerkt

### cookies
- sessionid (Session) cookie muss nicht vom nutzer zugestimmt werden, sollte aber in der datenschutzerklärung angegeben werden: https://www.datenschutz.org/session-cookie/
- csrftoken ist zur sicherheit gegen cross site request forgery, beinhaltet keinerlei personenbezogene daten

-> wir haben keine cookies denen man ausdrücklich zustimmen muss -> cookies akzeptieren popup ist nicht nötig

**Comment by Bishares** [comment]
Als Webseitenbetreiber habe ich mal Tobi angegeben. Evtl. brauchen wir noch eine service mail adresse für
- löschung des Nutzeraccounts
- Kontaktaufnahme mit dem Webseitenbetreiber

**Comment by Bishares** [comment]
was merged with pull request #114 

we still need a service mail with those features:

Als Webseitenbetreiber habe ich mal Tobi angegeben. Evtl. brauchen wir noch eine service mail adresse für

- löschung des Nutzeraccounts
- Kontaktaufnahme mit dem Webseitenbetreiber
