### ISSUE TITLE
Initial File Upload

### ISSUE THREAD

**Issue by h3ssto** [h3ssto/ddueruem-web#7]
Django app: `core`

### Backend Tasks
* [x] #14
    * Model name (mandatory)
    * Model description (optional, Markdown)
    * Uploader E-Mail, time and date?
    * License of the upload
* [x] #15
* [x] #27
   * delete it without recovery
   * make it instantaneously available (otherwise after 48h?)

### Frontend Tasks
* Add button to landing page (user logged in) for uploading
* [x] #26
    * Serving the file upload form
    * Opt-In that the uploader is legally allowed to share the model.
    * Opt-In that some data of the user (E-Mail) and some metrics regarding the user (IP?, time and date of the upload?) will be persistently kept (even after account deletion) for legal purposes.
    * Opt-In that all information given on upload will be open source (some CC license) and made publicly available on the app and the GitHub Mirror.

### Misc
* What data are we allowed to keep persistently for legal purposes?
* What is a suitable license (CC BY-SA 2.0?)?

**Comment by Eixix** [comment]
#27 now only contains the upload link, the delete function has been moved to another issue #28
