### ISSUE TITLE
Basic Analysis Support

### ISSUE THREAD

**Issue by h3ssto** [h3ssto/ddueruem-web#75]
[APP: analysis]

We need support for a variety of analysis. In order to facilitate them in a load-balanced manner, we delegate them to Docker runners. (In the long run, we will support Apache Mesos).

* Is it possible to use gitlab-runners (because we have them) for non-gitlab-jobs 
* What alternatives to we have that work similar and support
    * Timeouts
    * Memory limits
    * Persistent Storage
* Do we need/want more than docker-py?

#### Issue Milestones

* [ ] Implement an "analyze me" button on feature model views that runs a Docker container saying "Hello World". Once the Docker terminates, propagate the answer back to the frontend. Iterate, until we are happy with our stack.
* [ ] ...

**Comment by wurstbroteater** [comment]
see  #103 for prototype
