### ISSUE TITLE
Third party login

### ISSUE THREAD

**Issue by h3ssto** [h3ssto/ddueruem-web#8]
Django App: **TBD**

Investigate the feasibility of giving users the option to login using their GitHub, Google, or Twitter account.

 - Add github handle to user
 - Add twiter handle to user

**Comment by wurstbroteater** [comment]
Moved adding github and twitter handle from issue #11 to this issue

**Comment by wurstbroteater** [comment]
closed as it is not part of the first release

**Comment by h3ssto** [comment]
Please look into how much effort it would be to facilitate a Login via GitHub / Twitter with this: https://github.com/pennersr/django-allauth

**Comment by lukharsch** [comment]
...Github, Twitter Login?

**Comment by lukharsch** [comment]
Login with Github done, login with Twitter seems to be way more difficult than expected (oauth vs oauth2). Closing this for now.
