### ISSUE TITLE
Rework Feature Models to be part of a Feature Model Family

### ISSUE THREAD

**Issue by wurstbroteater** [h3ssto/ddueruem-web#98]
We need to refactor the Feature Models aka. `File`'s . To enhance tracking of FMs which are related to the same "group",  we need a new Field **Feature Model Family**.  A FMF is a group which contains all the versions of a Feature Model. There can not exist a Feature Model Family with less than 1 FM.  This also affects the creation or upload of a Feature Model.

##### Backend
Create new Field Feature Model Family and change file persistence such that:
When a new FM is uploaded, it will be placed in a folder with the same name as the Feature Model Family.
In this Folder, there should be a new folder with the same name as the FM label + the version.

###### Example:
**FMF:** myFMFamily
**FMLabel:** myLabel
**FileName:** Fm.xml
**newVersionOf:** -

results in:
- myFMFamily
    -  myLabel 0
        - Fm.xml
        - readme.md (contains Attributes like uploader, upload date ,....)
      
Now, we want to upload a new version of the FM myLabel. This could look like this:

**FMF:** myFMFamily
**FMLabel:** myNewLabel
**FileName:** Fm.xml
**newVersionOf:** myLabel
results in:
- myFMFamily
    -  myLabel 0
        - Fm.xml
        - readme.md 
    - myNewLabel 1
        - Fm.xml
        - readme.md 

**Problems**
From that structure it  remains unclear which FM is a new version of which FM.
- Is it important to see from this hierarchie that myNewLabel is new version of myLabel?

A possible solution could be to either have a "relations file" which store new version of information
or we could treat FM as FMFamilies eg: in the first case (upload myLabel) myLabel is consider as FM because it has no new version. In the second case (upload myNewLabel) we can treat myLabel as a FM Family and so we can save the FM myNewLabel in myLabel. This could look like this:

- myFMFamily
    -  myLabel 0
        - Fm.xml
        - readme.md (contains Attributes like uploader, upload date ,....)
        - myNewLabel 1
            - Fm.xml
            - readme.md (contains Attributes like uploader, upload date ,....)

**Problem**
This enhances the readability of the hierarchie but is it really bettter?

##### Frontend
Here we need to change the File Upload Form and  the Feature Model list.

**File Upload Changes**
For now on the user should be able to enter a new Feature Model Family name if the user wants to upload an entirly new FM. If a FMF name was entered this also means that the new_version_of field should not be clickable. 

In the other case, (the user wants to upload a new version of a FM) then the FMF name field should not be clickable because we can interfer to which FMF the FM belongs by checking the FMF of the previous version. As soon as a FM has been choosen as previous version, then display the FMF name in the (still not clickable/changeable) FMF name field.

**Comment by h3ssto** [comment]
I would suggest the following scheme:

* `myFMFamily`
    * `readme.md`
    * `model-<version1>`.xml
    * `model-<version2>`.xml

For almost all feature models for which multiple versions are known (e.g., https://github.com/PettTo/Feature-Model-History-of-Linux) version is some kind of date format. I would propose to append a "changelog" to the readme.md containing stuff like "on date x user y uploaded versions z". If a user uploads a "fix" that is not a new version of a feature model, then the respective file `model-<version>.xml` is simply overridden and a corresponding message is appended to the readme (maybe containing the commit hash where the old version can be found?).

**Comment by wurstbroteater** [comment]
@h3ssto : I dont like the idea of having the model.xml direclty inside the family folder for the following reason: If we start supporting other file formats (e.g. dimacs) the FMFamily folder becomes overcrowed like this
* `myFMFamily`
    * `readme.md`
    * `model-<version1>`.xml
    * `model-<version1>`.dimacs
    * `model-<version1>`.foo
    * `model-<version2>`.xml
    * `model-<version2>`.dimacs
    * `model-<version2>`.foo
   
  Now imagine this for a version rich FMFamily supporting xml and dimacs. In my opinion it is better to put models in a new folder or zip then rather then just pasting them into the FMF folder. 

Since you havent clearly adressed my concerns, I have to ask again:

- Is it important to see from the hierarchy which FM version belongs to which FM ?

I also suggested to save FM attributes in `readme.md`. With your format this becomes very tricky. We could just append new infos but handling a change here like altering an existing FM is painful to maintain.
- What stores the readme in your example?

**Comment by h3ssto** [comment]
I think we should just keep this for now, maybe it makes sense to segregate top level, so that the top level directories are `dimacs`, `sxfm` and so on, but for now, this should suffice. If they want a better overview => Look at our website :-D

**Comment by h3ssto** [comment]
With regards to the readme, I think it is only necessary to document the origin of the uploads and some global information on the models (description should be the same for all of them). Any statistics we have on a per model base, should be made available in a machine-readable format like csv.

**Comment by wurstbroteater** [comment]
> I would suggest the following scheme:
> 
> * `myFMFamily`
>   
>   * `readme.md`
>   * `model-<version1>`.xml
>   * `model-<version2>`.xml
> 
> For almost all feature models for which multiple versions are known (e.g., https://github.com/PettTo/Feature-Model-History-of-Linux) version is some kind of date format. I would propose to append a "changelog" to the readme.md containing stuff like "on date x user y uploaded versions z". If a user uploads a "fix" that is not a new version of a feature model, then the respective file `model-<version>.xml` is simply overridden and a corresponding message is appended to the readme (maybe containing the commit hash where the old version can be found?).

I used this scheme:
- myFMFamily
    -  someFM
        - Fm.xml
        - FM.dmiacs
        - readme.md 
    - someNewFM
        - Fm.xml
        - fm.foo
        - readme.md
    -  fmf_changelog
   
With this scheme, we do not need the the top level separation into dmiacs, sxfm and other file formats because they are all stored in the folder with the same name as the FM. Adding new versions to a FM (and therefore also to the FMF) is listed in fmf_changelog file
